---
# - name: "Initialize database"
#   throttle: 1
#   import_tasks: "database_init.yml"
#   when: "is_dev"

- name: "Create SBS group"
  group:
    name: "{{ sbs.group }}"
    state: "present"
  register: "result"

- name: "Save SBS group gid"
  set_fact:
    sbs_group_gid: "{{ result.gid }}"

- name: "Create SBS user"
  user:
    name: "{{ sbs.user }}"
    group: "{{ sbs.group }}"
    comment: "User to run SBS service"
    shell: "/bin/false"
    password: "!"
    home: "{{ sbs.conf_dir }}"
    create_home: false
    state: "present"
  register: "result"

- name: "Save sbs user uid"
  set_fact:
    sbs_user_uid: "{{ result.uid }}"

- name: "Create directories"
  file:
    path: "{{item.path}}"
    state: "directory"
    owner: "{{sbs_user_uid}}"
    group: "{{sbs_group_gid}}"
    mode: "{{item.mode}}"
  with_items:
    - { path: "{{sbs.work_dir}}",            mode: "0755" }
    - { path: "{{sbs.conf_dir}}",            mode: "0755" }
    - { path: "{{sbs.conf_dir}}/saml",       mode: "0755" }
    - { path: "{{sbs.log_dir}}",             mode: "0775" }
    - { path: "{{sbs.cert_dir}}",            mode: "0755" }

- name: "Fix file permissions"
  file:
    path: "{{sbs.log_dir}}/{{item}}"
    owner: "{{sbs_user_uid}}"
    group: "{{sbs_group_gid}}"
    mode: "0664"
    state: "touch"
    modification_time: "preserve"
    access_time: "preserve"
  with_items:
    - "sbs.log"
    - "sbs.debug.log"

# Create dummy file in certs dir to pacify container pre-init script
# https://github.com/SURFscz/SBS/pull/2312
- name: "Touch file in {{ sbs.cert_dir }}"
  ansible.builtin.file:
    path: "{{sbs.cert_dir}}/dummy"
    state: file

- name: "Create SBS config files"
  template:
    src: "{{item.name}}.j2"
    dest: "{{ sbs.conf_dir }}/{{item.name}}"
    owner: "{{sbs_user_uid}}"
    group: "{{sbs_group_gid}}"
    mode: "{{item.mode}}"
  with_items:
    - { name: "config.yml",      mode: "0644" }
    - { name: "alembic.ini",     mode: "0644" }
    - { name: "disclaimer.css",  mode: "0644" }
    - { name: "sbs-apache.conf", mode: "0644" }
  no_log: "{{sbs.ansible_nolog}}"
  notify: "Restart sbs containers"

- name: "Pull sbs image"
  community.docker.docker_image_pull:
    name: "{{ item }}"
  with_items:
    - "{{ sbs.client_image }}"
    - "{{ sbs.server_image }}"
  register: "sbs_image"

# We need to remove sram-static so it gets repopulated
# with new SBS image static content
- name: "Clean up old containers"
  block:
    - name: "Stop and remove sbs and sbs-server containers"
      community.docker.docker_container:
        name: "{{ item }}"
        state: "absent"
      with_items:
        - "sbs-client"
        - "sbs-server"

  when: "sbs_image is changed"

- name: "Run SBS migrations"
  throttle: 1
  community.docker.docker_container:
    name: "sbs-migration"
    image: "{{ sbs.server_image }}"
    pull: "never"
    state: "started"
    restart_policy: "no"
    detach: false
    env:
      RUNAS_UID: "{{ sbs_user_uid | string }}"
      RUNAS_GID: "{{ sbs_group_gid | string }}"
      MIGRATIONS_ONLY: "1"
    # don't actually run the server
    command: "/bin/true"
    volumes:
      - "{{ sbs.conf_dir }}:/sbs-config"
      - "{{ sbs.cert_dir }}:/sbs-config/cert:ro"
      - "{{ sbs.log_dir }}:/opt/sbs/log"
    networks:
      - name: "loadbalancer"
  register: "result"
  failed_when: "'container' not in result or result.container.State.ExitCode != 0"
  changed_when: "'[alembic.runtime.migration] Running upgrade' in result.container.Output"
  notify: "Restart sbs containers"

# Remove the migration container; we can do that with auto_remove, because if we use that, ansible
# will not save the output in result
- name: "Remove migration container"
  community.docker.docker_container:
    name: "sbs-migration"
    state: "absent"
  # TODO: fix this by only running this if "sbs_image is changed"
  changed_when: false

- name: "Start sbs client container"
  community.docker.docker_container:
    name: "sbs-client"
    image: "{{ sbs.client_image }}"
    pull: "never"
    restart_policy: "always"
    state: "started"
    volumes:
      - "{{ sbs.conf_dir }}/sbs-apache.conf:/etc/apache2/sites-enabled/sbs.conf:ro"
      - "{{ sbs.conf_dir }}/disclaimer.css:/opt/sbs/client/dist/disclaimer.css:ro"
    networks:
      - name: "loadbalancer"
    labels:
      traefik.http.routers.sbsclient.rule: "Host(`{{ sbs.base_domain }}`)"
      traefik.http.routers.sbsclient.tls: "true"
      traefik.enable: "true"

- name: "Start SBS server container"
  community.docker.docker_container:
    name: "sbs-server"
    image: "{{ sbs.server_image }}"
    restart_policy: "always"
    state: "started"
    env:
      RUNAS_UID: "{{ sbs_user_uid | string }}"
      RUNAS_GID: "{{ sbs_group_gid | string }}"
      CONFIG: "/opt/sbs/server/config/config.yml"
      REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
      RUN_MIGRATIONS: "0"
    pull: "never"
    volumes:
      - "{{ sbs.conf_dir }}:/sbs-config"
      - "{{ sbs.cert_dir }}:/sbs-config/cert:ro"
      - "{{ sbs.log_dir }}:/opt/sbs/log"
      - "/tmp/ci-runner:/tmp/ci-runner"
    networks:
      - name: "loadbalancer"
    # TODO: fix this: this is only for dev
    etc_hosts:
      oidc-op.scz-vm.net: "172.20.1.24"
      host.docker.internal: host-gateway
