---
- name: Create acme user
  ansible.builtin.user:
    name: "acme"
    state: "present"
    groups:
      - "lbops"
      - "haproxy"
    append: true

- name: Install acl package so ansible can run as an unprivilegd user
  ansible.builtin.package:
    name: "acl"
    state: "present"

- name: Clone the acme.sh repo
  ansible.builtin.git:
    repo: "https://github.com/acmesh-official/acme.sh.git"
    dest: "/opt/acmesh/"
    version: "3.1.0"
    update: true

- name: Install the acme.sh script
  ansible.builtin.shell:
    cmd: |
      sh /opt/acmesh/acme.sh --install --accountemail "{{ admin_email }}"
    chdir: "/opt/acmesh"
    creates: "/home/acme/.acme.sh/acme.sh"
  become: true
  become_user: "acme"

- name: Set email address in acme config
  ansible.builtin.lineinfile:
    path: "/home/acme/.acme.sh/account.conf"
    line: "ACCOUNT_EMAIL='{{ admin_email }}'"
    create: true
    owner: "acme"
    group: "acme"
    mode: "0600"

- name: Find CA account dir
  ansible.builtin.set_fact:
    haproxy_acme_ca_dir: "/home/acme/.acme.sh/ca/{{ haproxy_acme_server | replace('https://', '') }}"

- name: Create the acme account
  ansible.builtin.command:
    cmd: |
      /home/acme/.acme.sh/acme.sh
          --register-account
          --eab-kid "{{ haproxy_acme_eab_kid }}"
          --eab-hmac-key "{{ haproxy_acme_eab_hmac_key }}"
          --server "{{ haproxy_acme_server }}"
    creates: "{{ haproxy_acme_ca_dir }}/account.json"
  register: "acme_account"
  become: true
  become_user: "acme"

- name: Remove default cronjob for renewal
  ansible.builtin.file:
    path: "/var/spool/cron/crontabs/acme"
    state: "absent"

- name: Install cronjob for renewal
  ansible.builtin.copy:
    dest: "/etc/cron.d/acme-renew"
    owner: "root"
    group: "root"
    mode: "0644"
    content: |
      MAILTO=surfconext-beheer@surf.nl
      30 07    * *   {{ haproxy_acme_cronjob_dow }}    acme    /home/acme/.acme.sh/acme.sh --cron --home /home/acme/.acme.sh > /dev/null
      {%- if haproxy_acme_cronjob_monitor_url|bool and haproxy_acme_cronjob_monitor_url|length > 0 -%}
         {# #} && curl -fsS --retry 3 -o /dev/null {{ haproxy_acme_cronjob_monitor_url }}
      {%- endif %}
