---
- name: determine ldap admins
  set_fact:
    ldap_admins: "{{ sram_ldap_admins }}"

# Find existing ldap admins
- name: Initialize admins (I)
  community.general.ldap_search:
    dn: "{{ sram_ldap_services_dn.basedn }}"
    scope: "onelevel"
    filter: "(objectClass=organizationalRole)"
    attrs:
      - "cn"
    bind_dn: "{{ sram_ldap_services_dn.binddn }}"
    bind_pw: "{{ sram_ldap_services_password }}"
    server_uri: "{{sram_ldap_uri }}"
  register: "existing_ldap_admins_result"

# ansible trips over stuff like this: we need to extract the results from the result
- name: Initialize admins (Ia)
  set_fact:
    existing_ldap_admins: "{{ existing_ldap_admins_result.results }}"

# Remove LDAP non-admins
- name: Initialize admins (II)
  community.general.ldap_entry:
    dn: "cn={{ item.cn }},{{ sram_ldap_services_dn.basedn }}"
    state: absent
    bind_dn: "{{ sram_ldap_services_dn.binddn }}"
    bind_pw: "{{ sram_ldap_services_password }}"
    server_uri: "{{ sram_ldap_uri }}"
  when: >
    item.cn not in ldap_admins | map(attribute='uid')
    and item.cn != 'admin'
  loop: "{{existing_ldap_admins}}"

# Insert LDAP admins
- name: Initialize admins (III)
  community.general.ldap_entry:
    dn: "cn={{ item.uid }},{{ sram_ldap_services_dn.basedn }}"
    objectClass:
      - simpleSecurityObject
      - organizationalRole
    attributes:
      description: An LDAP administrator
      userPassword: "{{ item.pw_hash }}"
    bind_dn: "{{ sram_ldap_services_dn.binddn }}"
    bind_pw: "{{ sram_ldap_services_password }}"
    server_uri: "{{ sram_ldap_uri }}"
  loop: "{{ ldap_admins }}"

# Make sure passwords are updated for existing admins
- name: Initialize admins (IV)
  community.general.ldap_attrs:
    dn: "cn={{ item.uid }},{{ sram_ldap_services_dn.basedn }}"
    attributes:
      userPassword: "{{ item.pw_hash }}"
    bind_dn: "{{ sram_ldap_services_dn.binddn }}"
    bind_pw: "{{ sram_ldap_services_password }}"
    server_uri: "{{ sram_ldap_uri }}"
  loop: "{{ ldap_admins }}"

