---
- name: Restart redis container
  community.docker.docker_container:
    name: sram-redis
    state: started
    restart: true
  when: redis_container is success and redis_container is not change
