---
- name: "Install python modules"
  ansible.builtin.package:
    name:
      - "python3-dateutil"
    state: "present"
  notify:
    - "Restart rsyslog"

# The server uses a different set of keys than the client
- name: "Put rsyslog server key"
  ansible.builtin.copy:
    content: "{{ rsyslogserverkey }}"
    dest: "/etc/pki/rsyslog/rsyslogserver.key"
    mode: "0400"

- name: "Create directory to save the logs"
  ansible.builtin.file:
    path: "{{ rsyslog_dir }}"
    owner: "root"
    group: "{{ rsyslog_read_group }}"
    mode: "0750"

- name: "Put rsyslog server certificate"
  ansible.builtin.copy:
    src: "{{ inventory_dir }}/files/certs/rsyslog/rsyslogserver.crt"
    dest: "/etc/pki/rsyslog/rsyslogserver.crt"
    mode: "0644"
    owner: "root"
    group: "adm"
  notify:
    - "Restart rsyslog"

- name: "Create directories to keep configuration file"
  ansible.builtin.file:
    path: "/etc/rsyslog.d/{{ item }}"
    mode: "0755"
    state: "directory"
  with_items:
    - "listeners"
    - "rulesets"
    - "templates"

- name: "Create template configurations"
  ansible.builtin.template:
    src: "sc_template.conf.j2"
    dest: "/etc/rsyslog.d/templates/{{ item.name }}.conf"
    backup: true
    mode: "0644"
  vars:  # use a semantic name in the template
    env_name: "{{ item.name }}"
  loop: "{{ rsyslog_environments }}"
  loop_control:
    label: "{{ item.name }}"
  notify:
    - "Restart rsyslog"

- name: "Create ruleset configurations"
  ansible.builtin.template:
    src: "sc_ruleset.conf.j2"
    dest: "/etc/rsyslog.d/rulesets/{{ item.name }}.conf"
    backup: true
    mode: "0644"
  vars:  # use a semantic name in the template
    env_name: "{{ item.name }}"
  loop: "{{ rsyslog_environments }}"
  loop_control:
    label: "{{ item.name }}"
  notify:
    - "Restart rsyslog"

- name: "Create sc listener configurations"
  ansible.builtin.template:
    src: "listener.conf.j2"
    dest: "/etc/rsyslog.d/listeners/{{ item.name }}.conf"
    backup: true
    mode: "0644"
  vars:  # use a semantic name in the template
    env_name: "{{ item.name }}"
    port: "{{ item.port }}"
    peer: "{{ item.permittedpeer }}"
  loop: "{{ rsyslog_environments }}"
  loop_control:
    label: "{{ item.name }}"
  notify:
    - "Restart rsyslog"

- name: "Create logrotate file for apps and host logs"
  ansible.builtin.template:
    src: "centralsyslog.j2"
    dest: "/etc/logrotate.d/centralsyslog"
    mode: "0644"

- name: "Put log empty warn script and cronjob"
  when: "rsyslog_enable_warn_empty_script"
  block:
    - name: "Put log empty script"
      ansible.builtin.template:
        src: "warn-empty-log.sh.j2"
        dest: "{{ rsyslog_checkemptylogs_dir }}/warn-empty-log.sh"
        backup: true
        mode: "0644"

    - name: "Create cronjob"
      ansible.builtin.cron:
        name: "check empty logs"
        minute: "{{ rsyslog_checkemptylogs_cron_minute | str }}"
        hour: "{{ rsyslog_checkemptylogs_cron_hour | str }}"
        weekday: "{{ rsyslog_checkemptylogs_cron_weekdays }}"
        job: "{{ rsyslog_checkemptylogs_dir }}/warn-empty-log.sh -m"
