#!/bin/bash
set -e
if [ "$#" -ne 3 ]
then
  echo "Usage: ./provision-test [YOUR_USERNAME_ON_TARGET_HOSTS] [ABSOLUTE_PATH_TO_SECRETS_FILE] [COMPONENT_NAME]"
  exit 1
fi

COMPONENTS=("authz-admin" "authz-playground" "authz-server" "engineblock" "service-registry" "teams" "voot")
VALID_COMPONENT=0
for component in "${COMPONENTS[@]}"
do
  if [ "$3" == $component ]; then
    VALID_COMPONENT=1
    break
  fi
done
if [ $VALID_COMPONENT = 0 ]; then
  echo "The component $3 is not a valid component";
  exit 1
fi

./ansible-env test provision-test.yml "$1" "$2" --tags "$3"
