#!/bin/bash
set -e
vagrant up openconext-vm
./ansible-env vm openconext-generate-certs-vm.yml
./ansible-env vm openconext-all.yml
./ansible-env vm openconext-vm.yml
./ansible-env vm openconext-storage.yml
./ansible-env vm openconext-vm-initial.yml
./ansible-env vm openconext-java.yml
./ansible-env vm openconext-php.yml
./ansible-env vm openconext-mujina.yml
