#!/bin/bash
set -e

case "$1" in
    "reload")
        echo "Reloading vagrant without provisioning"
        ENV='develop' vagrant reload
        ;;
    "up")
        echo "Running vagrant up without provisioning"
        ENV='develop' vagrant up
        ;;
    "migrate")
        echo "Running migrations"
        vagrant ssh apps -c /opt/openconext/OpenConext-engineblock/bin/migrate
        ;;
    "logparse")
        vagrant ssh apps -c "sudo tail -f /var/log/messages | /opt/openconext/OpenConext-engineblock/bin/logparse.sh"
        ;;
    "provision")
        echo "Provisioning"
        ansible-playbook -i inventory/vm -u vagrant provision-vm.yml --extra-vars="secrets_file=secrets/vm.yml develop=true"
        ;;
    *)
        echo "Running vagrant up with provisioning"
        ENV='develop' vagrant up
        ansible-playbook -i inventory/vm -u vagrant provision-vm.yml --extra-vars="secrets_file=secrets/vm.yml develop=true"
        ;;
esac


