#!/bin/bash
set -e

case "$1" in
    "install")
        echo "Running vagrant up with provisioning"
        ENV='develop' vagrant up
        ansible-playbook -i inventory/vm -u vagrant provision-vm.yml --extra-vars="secrets_file=secrets/vm.yml develop=true"
        ;;
    "up")
        echo "Running vagrant up without provisioning"
        ENV='develop' vagrant up
        ;;
    "provision")
        echo "Provisioning"
        ansible-playbook -i inventory/vm -u vagrant provision-vm.yml --extra-vars="secrets_file=secrets/vm.yml develop=true"
        ;;
    "reload")
        echo "Reloading vagrant without provisioning"
        ENV='develop' vagrant reload
        ;;
    "migrate")
        echo "Running migrations"
        vagrant ssh apps -c /opt/openconext/OpenConext-engineblock/bin/migrate
        ;;
    *)
        echo "Usage: $0 {install|up|provision|reload|migrate}"
        ;;
esac


