---
- name: Make sure clients sync directory exists
  file:
    path: "{{ sram_plsc_conf_dir }}"
    state: directory
    mode: "0755"

- name: "Create plsc.yml source if it doesn't exist"
  template:
    src: "plsc.yml.j2"
    dest: "{{ sram_plsc_conf_dir }}/plsc.yml"
    mode: "0640"
  no_log: "{{ sram_plsc_ansible_nolog }}"
  notify: "Restart the plsc container"

- name: Create the plsc container
  community.docker.docker_container:
    name: "sram-plsc"
    image: "{{ sram_plsc_image }}"
    restart_policy: "always"
    state: started
    pull: true
    mounts:
      - type: bind
        source: "{{ sram_plsc_conf_dir }}/plsc.yml"
        target: "/opt/plsc/plsc.yml"
    networks:
      # TODO: Should this not be parametrized?
      - name: "loadbalancer"
