---
plsc_image: "ghcr.io/surfscz/sram-plsc:main"
plsc_conf_dir: "{{current_release_appdir}}/sram/plsc"
plsc_ansible_nolog: false
plsc_ldap_uri: "ldap://ldap:389/"
plsc_ldap_basedn: "dc=services,dc=vnet"
plsc_ldap_binddn: "cn=admin,dc=vnet"
plsc_ldap_password: "secret"
plsc_sbs_host: "http://sbs-server:8080"
plsc_sbs_user: "sysread"
plsc_sbs_password: "secret"
plsc_retry: 3
