---
sram_plsc_image: "ghcr.io/surfscz/sram-plsc:main"
sram_plsc_conf_dir: "{{current_release_appdir}}/sram/plsc"
sram_plsc_ansible_nolog: false
sram_plsc_ldap_uri: "ldap://ldap:389/"
sram_plsc_ldap_basedn: "dc=services,dc=vnet"
sram_plsc_ldap_binddn: "cn=admin,dc=vnet"
sram_plsc_ldap_password: "secret"
sram_plsc_sbs_host: "http://sbs-server:8080"
sram_plsc_sbs_user: "sysread"
sram_plsc_sbs_password: "secret"
sram_plsc_retry: 3
