FROM ansible/centos7-ansible:stable

COPY ./roles /ansible/roles
COPY ./group_vars /ansible/group_vars
COPY ./host_vars /ansible/host_vars
COPY ./tests/test.sh /ansible/test.sh
COPY ./provision-vm.yml /ansible/provision-vm.yml
COPY ./inventory/docker /ansible/inventory/docker
COPY ./secrets/vm.yml /ansible/secrets/vm.yml

WORKDIR /ansible
ENTRYPOINT ["./test.sh"]
