FROM rockylinux:9
ENV container=docker

RUN rm -f /lib/systemd/system/multi-user.target.wants/*;\
    rm -f /etc/systemd/system/*.wants/*;\
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*;\
    rm -f /lib/systemd/system/anaconda.target.wants/*;

RUN yum clean all && \
    yum -y update && \
    yum -y install epel-release && \
    yum -y install git ansible iproute systemd cronie procps-ng

RUN echo -e '[local]\nlocalhost' > /etc/ansible/hosts

VOLUME [ "/sys/fs/cgroup" ]

CMD ["/usr/sbin/init"]
