---
# - name: "enable pyff-metadata job"
#   systemd:
#     name: "pyff-metadata.timer"
#     enabled: true
#     state: "started"
#     daemon_reload: true

# - name: "run pyff-metadata job"
#   systemd:
#     name: "pyff-metadata.service"
#     state: "started"
#     daemon_reload: true

- name: Restart the pyFF container
  community.docker.docker_container:
    name: "sram-metadata-pyff"
    restart: true
    state: started
