---
# In this task file the cluster is configured

# priority moet matchen met replication role, of replication role uit cluster mebers halen?
# todo write concern zetten

# Do some preflight checks
- name: Check some cluster related variables
  when: mongo_mode == "cluster"
  block:
    - name: Fail on undefined replica_set_name
      when: mongo_replica_set_name is not defined
      ansible.builtin.fail:
        msg: "Something is wrong, mongo_mode was set to cluster but replica_set_name is undefined."

- name: Debug replica settings
  ansible.builtin.debug:
    msg: "Replica set name {{ mongo_replica_set_name }}"
    verbosity: 2

# Who is primary
- name: Identify designated primary
  ansible.builtin.set_fact:
    mongo_primary_host: >-
      {{
        groups['mongo_servers']
        | map('extract', hostvars)
        | selectattr('mongo_replication_role', 'defined')
        | selectattr('mongo_replication_role', 'equalto', 'primary')
        | map(attribute='inventory_hostname')
        | first
      }}
  failed_when: mongo_primary_host is not defined or mongo_primary_host == ''

- name: Debug primary settings
  ansible.builtin.debug:
    msg: "Primary is {{ mongo_primary_host }}"
    verbosity: 2

# What is the replication role of the current host
- name: Debug replication role settings
  ansible.builtin.debug:
    msg: "This nodes replication role is {{ mongo_replication_role }}"
    verbosity: 2

# Cannot initialise a cluster without starting.......
- name: Enable and start mongod
  ansible.builtin.service:
    name: mongod.service
    enabled: true
    state: started

# Initialise cluster block
- name: initialise or reconfigure cluster block
  when: mongo_replication_role == 'primary'
  block:
    - name: Check if replica set is already initialised
      community.mongodb.mongodb_shell:
        login_host: localhost
        login_user: admin
        login_port: "{{ mongo_port }}"
        login_password: "{{ mongo_admin_password }}"
        eval: "rs.status().ok"
        db: admin
      register: rs_already_init
      ignore_errors: true

    - name: Debug cluster initialization check
      ansible.builtin.debug:
        msg: "{{ rs_already_init }}"
        verbosity: 2

    # This should be possible with community.mongodb.mongodb_replicaset
    # But we keep getting authenticatione error so leave it like this for now
    - name: Initialise replica set if necessary
      community.mongodb.mongodb_shell:
        login_host: localhost
        login_user: admin
        login_port: "{{ mongo_port }}"
        login_password: "{{ mongo_admin_password }}"
        eval: |
          rs.initiate({
            _id: "{{ mongo_replica_set_name }}",
            members: [
              {% for m in mongo_cluster_members %}
              { _id: {{ loop.index0 }}, host: "{{ m.host }}", priority: {{ m.priority }}, votes: {{ m.votes }}{% if m.arbiterOnly is defined and m.arbiterOnly and m.arbiterOnly == true %}, arbiterOnly: true {% endif %} }{{ "," if not loop.last else "" }}
              {% endfor %}
            ]
          })
        db: admin
      when: rs_already_init.failed
      register: rs_init

    - name: Debug cluster initialization
      ansible.builtin.debug:
        msg: "{{ rs_init }}"
        verbosity: 2

    # Reconfigure cluster
    - name: Reconfigure cluster if necessary
      community.mongodb.mongodb_replicaset:
        login_host: localhost
        login_user: admin
        login_password: "{{ mongo_admin_password }}"
        login_port: "{{ mongo_port }}"
        reconfigure: true
        replica_set: "{{ mongo_replica_set_name }}"
        members: "{{ mongo_cluster_members }}"
      register: rs_reconfigure

    - name: Debug cluster reconfiguration
      ansible.builtin.debug:
        msg: "{{ rs_reconfigure }}"
        verbosity: 2

    - name: Wait for the replicaset to stabilise
      community.mongodb.mongodb_status:
        replica_set: "{{ mongo_replica_set_name }}"
        login_host: localhost
        login_user: admin
        login_password: "{{ mongo_admin_password }}"
        login_port: "{{ mongo_port }}"
        poll: 5
        interval: 30

    # Cluster settings that cannot be changed with mongodb_replicaset

    - name: Get current default write concern
      community.mongodb.mongodb_shell:
        login_host: localhost
        login_port: 27017
        login_user: admin
        login_password: "{{ mongo_admin_password }}"
        eval: "db.adminCommand({ getDefaultRWConcern: 1 })"
        #transform: raw
      register: current_write_concern
      changed_when: false

    - name: Debug write concern check
      ansible.builtin.debug:
        msg: "{{ current_write_concern.transformed_output.defaultWriteConcern }}"
        verbosity: 2

    - name: Set default write concern
      community.mongodb.mongodb_shell:
        login_host: localhost
        login_user: admin
        login_password: "{{ mongo_admin_password }}"
        login_port: "{{ mongo_port }}"
        eval: "db.adminCommand({ setDefaultRWConcern: 1, defaultWriteConcern: { w: {{ mongo_cluster_write_concern | default('majority') }}, wtimeout: {{ mongo_cluster_write_timeout | default(5000) }} } })"
      when: >
          current_write_concern.transformed_output.defaultWriteConcern.w | string != mongo_cluster_write_concern | default('majority') | string
          or
          current_write_concern.transformed_output.defaultWriteConcern.wtimeout | int != mongo_cluster_write_timeout | default(5000) | int