---
# In this task file the cluster is configured

# todo rs.add add stees opnieuw dat willen we niet
# todo arbiter optie
# todo set votes, priority, hidden (uit hostvars?)
# priority moet matchen met replication role, of replication role uit cluster mebers halen?
# todo write concern zetten
# todo test alle servers leeg in 1 keer deployen
# todo test primary eerst dan secundaries
# todo test config wijziging zonder cluster wijziging
# todo node verwijderen
# todo prio wijzigen

- name: Check some cluster related variables
  when: mongo_mode == "cluster"
  block:
    - name: Fail on undefined replica_set_name
      when: mongo_replica_set_name is not defined
      ansible.builtin.fail:
        msg: "Something is wrong, mongo_mode was set to cluster but replica_set_name is undefined."

- name: Debug replica settings
  ansible.builtin.debug:
    msg: "Replica set name {{ mongo_replica_set_name }}"
    verbosity: 2

- name: Identify designated primary
  ansible.builtin.set_fact:
    mongo_primary_host: >-
      {{
        groups['mongo_servers']
        | map('extract', hostvars)
        | selectattr('mongo_replication_role', 'defined')
        | selectattr('mongo_replication_role', 'equalto', 'primary')
        | map(attribute='inventory_hostname')
        | first
      }}
  failed_when: mongo_primary_host is not defined or mongo_primary_host == ''

# Who is primary
- name: Debug primary settings
  ansible.builtin.debug:
    msg: "Primary is {{ mongo_primary_host }}"
    verbosity: 2

# What is the replication role of the current host
- name: Debug replication role settings
  ansible.builtin.debug:
    msg: "This nodes replication role is {{ mongo_replication_role }}"
    verbosity: 2

- name: Enable and start mongod
  ansible.builtin.service:
    name: mongod.service
    enabled: true
    state: started

- name: Initial cluster initialisation
  community.mongodb.mongodb_replicaset:
    login_host: localhost
    login_user: admin
    login_port: "{{ mongo_port }}"
    login_password: "{{ mongo_admin_password }}"
    replica_set: "{{ mongo_replica_set_name }}"
    members: "{{ mongo_cluster_members }}"
    validate: false
  run_once: true
  when: mongo_replication_role == 'primary'

# - name: Add members to cluster
#   when: mongo_replication_role != "primary"
#   block:
#     - name: Add new mongo server to replication set
#       when: mongo_replication_role != "arbiter"
#       community.mongodb.mongodb_shell:
#         login_host: localhost
#         login_user: admin
#         login_password: "{{ mongo_admin_password }}"
#         login_database: admin
#         eval: 'rs.add({ host: "{{ ansible_hostname }}:{{ mongo_port }}" })'
#       register: rs_add
#       delegate_to: "{{ mongo_primary_host }}"

    # - name: Debug rs add event
    #   ansible.builtin.debug:
    #     var: rs_add
    #     verbosity: 2