---
# In this task file the cluster is configured

# todo overrule serial for cluster initialize https://stackoverflow.com/questions/50026802/override-ansible-playbook-serial-from-command-line
# todo arbiter optie
# todo set votes, priority, hidden (uit hostvars?)
# priority moet matchen met replication role, of replication role uit cluster mebers halen?
# todo write concern zetten

# testen
# todo test alle servers leeg in 1 keer deployen
# todo test primary eerst dan secundaries
# todo test config wijziging zonder cluster wijziging
# todo node verwijderen of andere reconfiguring

- name: Check some cluster related variables
  when: mongo_mode == "cluster"
  block:
    - name: Fail on undefined replica_set_name
      when: mongo_replica_set_name is not defined
      ansible.builtin.fail:
        msg: "Something is wrong, mongo_mode was set to cluster but replica_set_name is undefined."

- name: Debug replica settings
  ansible.builtin.debug:
    msg: "Replica set name {{ mongo_replica_set_name }}"
    verbosity: 2

- name: Identify designated primary
  ansible.builtin.set_fact:
    mongo_primary_host: >-
      {{
        groups['mongo_servers']
        | map('extract', hostvars)
        | selectattr('mongo_replication_role', 'defined')
        | selectattr('mongo_replication_role', 'equalto', 'primary')
        | map(attribute='inventory_hostname')
        | first
      }}
  failed_when: mongo_primary_host is not defined or mongo_primary_host == ''

# Who is primary
- name: Debug primary settings
  ansible.builtin.debug:
    msg: "Primary is {{ mongo_primary_host }}"
    verbosity: 2

# What is the replication role of the current host
- name: Debug replication role settings
  ansible.builtin.debug:
    msg: "This nodes replication role is {{ mongo_replication_role }}"
    verbosity: 2

- name: Enable and start mongod
  ansible.builtin.service:
    name: mongod.service
    enabled: true
    state: started

- name: initialise cluster
  when: mongo_replication_role == 'primary'
  block:

    - name: Check if replica set is already initialised
      community.mongodb.mongodb_shell:
        login_host: localhost
        login_user: admin
        login_port: "{{ mongo_port }}"
        login_password: "{{ mongo_admin_password }}"
        eval: "rs.status().ok"
        db: admin
      register: rs_already_init
      ignore_errors: true

    - name: Initialise replica set (if not already done)
      community.mongodb.mongodb_shell:
        login_host: localhost
        login_user: admin
        login_port: "{{ mongo_port }}"
        login_password: "{{ mongo_admin_password }}"
        eval: |
          rs.initiate({
            _id: "{{ mongo_replica_set_name }}",
            members: [
              {% for m in mongo_cluster_members %}
              { _id: {{ loop.index0 }}, host: "{{ m.host }}", priority: {{ m.priority }}, votes: {{ m.votes }} }{{ "," if not loop.last else "" }}
              {% endfor %}
            ]
          })
        db: admin
      when: rs_already_init.failed or rs_already_init.transformed_output[0] != 1
      register: rs_init

    # - name: Initial cluster initialisation
    #   community.mongodb.mongodb_replicaset:
    #     login_host: localhost
    #     login_user: admin
    #     login_port: "{{ mongo_port }}"
    #     login_password: "{{ mongo_admin_password }}"
    #     replica_set: "{{ mongo_replica_set_name }}"
    #     members: "{{ mongo_cluster_members }}"
    #     validate: false # todo moet dat niet true zijn
    #   run_once: true
    #   when: mongo_replication_role == 'primary'

# - name: Add members to cluster
#   when: mongo_replication_role != "primary"
#   block:
#     - name: Add new mongo server to replication set
#       when: mongo_replication_role != "arbiter"
#       community.mongodb.mongodb_shell:
#         login_host: localhost
#         login_user: admin
#         login_password: "{{ mongo_admin_password }}"
#         login_database: admin
#         eval: 'rs.add({ host: "{{ ansible_hostname }}:{{ mongo_port }}" })'
#       register: rs_add
#       delegate_to: "{{ mongo_primary_host }}"

    # - name: Debug rs add event
    #   ansible.builtin.debug:
    #     var: rs_add
    #     verbosity: 2