---
# Assert if database_clients is a list or the ip will be chopped into characters and
# a user will be created for each character
- name: Assert if database_clients is a list
  ansible.builtin.assert:
    that: >
          ( database_clients is defined ) and
          and ( database_clients is iterable ) and ( database_clients is not string )

- name: "Debug create database users"
  ansible.builtin.debug:
    msg: "{{ item }}"
    verbosity: 2
  loop: "{{ databases.users | product(database_clients) | list }}"
  loop_control:
    label: "{{ item[0].name }}@{{ item[1] }}"

- name: "Create database users"
  community.mysql.mysql_user:
    name: "{{ item[0].name }}"
    host: "{{ item[1] }}"
    password: "{{ item[0].password }}"
    priv: "{{ item[0].db_name }}.*:{{ item[0].privilege }}"
    state: "present"
    append_privs: true
    login_unix_socket: "/var/lib/mysql/mysql.sock"
  run_once: true
  loop: "{{ databases.users | product(database_clients) | list }}"
  loop_control:
    label: "{{ item[0].name }}@{{ item[1] }}"
