---
- name: "Create database users"
  community.mysql.mysql_user:
    name: "{{ item[0].name }}"
    host: "{{ item[1] }}"
    password: "{{ item[0].password }}"
    priv: "{{ item[0].db_name }}.*:{{ item[0].privilege }}"
    state: "present"
    append_privs: true
    login_unix_socket: "/var/lib/mysql/mysql.sock"
  run_once: true
  loop: "{{ databases.users | product(database_clients) | list }}"
  loop_control:
    label: "{{ item[0].name }}@{{ item[1] }}"
