---
- name: Restart the plsc container
  community.docker.docker_container:
    name: sram-plsc
    restart: true
    state: started
  when: plsc_container is success and plsc_container is not change
