---
- name: "create self-signed Metadata Signing SSL certs"
  shell:
    cmd: '
      openssl genrsa -out "{{ sram_metadata_basedir }}/certs/signing.key" 2048;
      openssl req -new -nodes -x509 -subj "/C=NL/CN=signing"
                  -days 3650 -key "{{ sram_metadata_basedir }}/certs/signing.key"
                  -out "{{ sram_metadata_basedir }}/certs/signing.crt" -extensions v3_ca;
      chown {{sram_metadata_user}}:{{sram_metadata_group}} {{ sram_metadata_basedir }}/certs/*;
    '
    creates: "{{ sram_metadata_basedir }}/certs/signing.crt"
  when: "sram_metadata_signing_cert is not defined"
  notify: "Restart the pyFF container"

- name: "Write fixed Metadata signing certificates"
  copy:
    dest: "{{ sram_metadata_basedir }}/certs/{{ item.file }}"
    content: "{{item.contents}}"
    mode: "{{item.mode}}"
    owner: "{{sram_metadata_user}}"
    group: "{{sram_metadata_group}}"
  with_items:
    - { file: "signing.key", mode: "0640", contents: "{{sram_metadata_signing_cert.priv}}" }
    - { file: "signing.crt", mode: "0644", contents: "{{sram_metadata_signing_cert.pub}}"  }
  when: "sram_metadata_signing_cert is defined"
  notify: "Restart the pyFF container"

- name: "Copy source certificates"
  copy:
    src: "{{ item }}"
    dest: "{{ sram_metadata_basedir }}/certs"
    mode: "0644"
  with_items:
    - "surfconext.crt"
  notify: "Restart the pyFF container"

- name: "Install IdP metadata"
  copy:
    content: "{{item.metadata}}"
    dest: "{{ sram_metadata_basedir }}/src/{{item.name}}.xml"
    mode: "0644"
  with_items: "{{ sram_metadata_idps_files }}"
  notify: "Restart the pyFF container"

- name: "Copy pyFF xslt transformations"
  copy:
    src: "{{item}}"
    dest: "{{sram_metadata_basedir}}/xslt"
    mode: "0644"
  with_items:
    - "transform_proxy.xslt"
    - "transform.xslt"
  notify: "Restart the pyFF container"

- name: "Copy pyFF feeds"
  copy:
    src: "{{item}}"
    dest: "{{sram_metadata_basedir}}/feeds"
    mode: "0644"
  with_items:
    - "01_idps.fd"
    - "02_backend.fd"
    - "03_frontend.fd"
  notify: "Restart the pyFF container"

- name: "Create the pyFF container"
  community.docker.docker_container:
    name: "sram-metadata-pyff"
    image: "{{ sram_metadata_image_pyff }}"
    restart_policy: "always"
    state: "started"
    pull: true
    init: true
    env:
      USER: "{{ metadata_user_uid | string }}"
      GROUP: "{{ metadata_group_gid | string }}"
    mounts:
      - source: "{{ sram_metadata_basedir }}/web"
        target: "/opt/pyff/web"
        type: "bind"
      - source: "{{ sram_metadata_basedir }}/feeds"
        target: "/opt/pyff/feeds"
        type: "bind"
        read_only: true
      - source: "{{ sram_metadata_basedir }}/src"
        target: "/opt/pyff/src"
        type: "bind"
        read_only: true
      - source: "{{ sram_metadata_basedir }}/certs"
        target: "/opt/pyff/certs"
        type: "bind"
        read_only: true
      - source: "{{ sram_metadata_basedir }}/xslt"
        target: "/opt/pyff/xslt"
        type: "bind"
        read_only: true
    healthcheck:
      test:
        - "CMD"
        - "bash"
        - "-c"
        - "[[ $(($(date +%s)-$(date -r /opt/pyff/web/idps.xml +%s))) -lt 400 ]]"
      interval: "10s"
      timeout: "5s"
      retries: 3
      start_period: "5s"
