DEF = "urn:mace:dir:attribute-def:"
TERENA = "urn:mace:terena.org:attribute-def:"
OID = "urn:oid:"

MAP = {
    "identifier": "urn:oasis:names:tc:SAML:2.0:attrname-format:basic",
    "fro": {
        f"{TERENA}schacHomeOrganization": "schacHomeOrganization",
        f"{DEF}cn": "cn",
        f"{DEF}displayName": "displayName",
        f"{DEF}eduPersonAffiliation": "eduPersonAffiliation",
        f"{DEF}eduPersonEntitlement": "eduPersonEntitlement",
        f"{DEF}eduPersonPrincipalName": "eduPersonPrincipalName",
        f"{DEF}eduPersonScopedAffiliation": "eduPersonScopedAffiliation",
        f"{DEF}eduPersonTargetedID": "eduPersonTargetedID",
        f"{DEF}eduPersonAssurance": "eduPersonAssurance",
        f"{DEF}mail": "mail",
        f"{DEF}emailAddress": "emailAddress",
        f"{DEF}givenName": "givenName",
        f"{DEF}gn": "gn",
        f"{DEF}isMemberOf": "isMemberOf",
        f"{DEF}member": "member",
        f"{DEF}name": "name",
        f"{DEF}sn": "sn",
        f"{DEF}surname": "surname",
        f"{DEF}uid": "uid",
        f"{OID}1.3.6.1.4.1.25178.4.1.6": "voPersonId",
    },
    "to": {
        "schacHomeOrganization": f"{TERENA}schacHomeOrganization",
        "cn": f"{DEF}cn",
        "displayName": f"{DEF}displayName",
        "eduPersonAffiliation": f"{DEF}eduPersonAffiliation",
        "eduPersonEntitlement": f"{DEF}eduPersonEntitlement",
        "eduPersonPrincipalName": f"{DEF}eduPersonPrincipalName",
        "eduPersonScopedAffiliation": f"{DEF}eduPersonScopedAffiliation",
        "eduPersonTargetedID": f"{DEF}eduPersonTargetedID",
        "eduPersonAssurance": f"{DEF}eduPersonAssurance",
        "eduPersonOrcid": f"{DEF}eduPersonOrcid",
        "mail": f"{DEF}mail",
        "emailAddress": f"{DEF}emailAddress",
        "givenName": f"{DEF}givenName",
        "gn": f"{DEF}gn",
        "isMemberOf": f"{DEF}isMemberOf",
        "member": f"{DEF}member",
        "name": f"{DEF}name",
        "sn": f"{DEF}sn",
        "surname": f"{DEF}surname",
        "uid": f"{DEF}uid",
        "voPersonId": f"{OID}1.3.6.1.4.1.25178.4.1.6",
    },
}
