#!/bin/bash

set -e
set -o pipefail

ENV=$1
shift
if [ -z "$ENV" ]
then
    echo "Please specify environment"
    exit 1
fi


SECRET=
if [ -n "$1" ]
then
    SECRET=$1
    shift
fi

# aliases
if [ "$ENV" = "prd" ]
then
    ENV=prod
fi

# check if env is correct
if [ "$ENV" != "acc" ] && [ "$ENV" != "prod" ] && [ "$ENV" != "test" ] && [ "$ENV" != "test2" ]
then
    echo "Unknown environment '$ENV'"
    echo "Acceptable are: acc, pro?d, test, test2"
    exit 1
fi

CMD="ansible-vault encrypt_string --encrypt-vault-id=$ENV"
if [ -n "$SECRET" ]
then
    CMD="$CMD $SECRET"
fi

$CMD | sed 's/^ \+/  /'
echo

exit 0
