#!/bin/bash
#
# This script will generate new password, secrets and certificates for OpenConext.
# 
# It is to be used before any Ansible command.
#
# When a password must be sha-encoded, the clear-text password must be set before the sha-encoded
# Key for the sha-encoded password must be the same as the clear-text password with the '_sha'
#

SECRET_VARS_FILE=../secrets/secret-vars.yml
SECRET_VARS_TEMPLATE_FILE=../secrets/secret-vars-template.yml
# ----- End configuration

# ----- Input handling
if [ $# -eq 0 ]
  then
    echo "INFO: No arguments supplied, using default file location" $SECRET_VARS_FILE
fi

if [ $# -gt 1 ]
  then
    echo "ERROR: Only 1 argument expected please supply only the file containing the secrets, for example " $SECRET_VARS_FILE
    exit 1
fi
# ----- End Input handing

if [ $# -eq 1 ]
  then
    SECRET_VARS_FILE=$1
    echo "INFO: Using file " $SECRET_VARS_FILE " for containing the secrets. Note you must pass this file into you env as well!"
fi 

set -e
#set -x

tempfile() {
    tempprefix=$(basename "$0")
    mktemp /tmp/${tempprefix}.XXXXXX
}


SV_FILE=$(tempfile)
trap 'rm -f $SV_FILE; echo "Error: Operation not completed, please restart command"' EXIT INT TERM 

while IFS= read -r line
do
  if [ -z "$line" ]; then
    echo "" >> $SV_FILE
    continue
  fi
  if [ "$line" != "${line#\#}" ]; then
    echo "$line" >> $SV_FILE
    continue
  fi

  key=$(printf "%s" "$line" | cut -f1 -d:)  
  value=$(echo $line | cut -f2 -d: | xargs)
  
  if [ "$value" == 'sha' ]; then
    # sha-key must be later in template file
    # lookup password for the non-sha variant (engine_ldap_password for engine_ldap_password_sha)
    # run command echo -n secret | sha1sum
    # where secret is the password
    passwordkey=`echo $key | sed 's/_sha$//g'`
    passwordline=`cat $SV_FILE | grep $passwordkey`
    password=$(echo $passwordline | cut -f2 -d:)
    sha=`echo -n $password | sha1sum | cut -f1 -d ' '`
    line="$key: {sha}$sha"
    echo "$line" >> $SV_FILE
    continue
  fi

  if [ "$value" == 'salt' ]; then
    salt=`tr -c -d '0123456789abcdefghijklmnopqrstuvwxyz' </dev/urandom | dd bs=32 count=1 2>/dev/null;echo`
    line="$key: $salt "
    echo "$line" >> $SV_FILE
    continue
  fi


  if [ "$value" == 'secret' ]; then
    password=`(tr -cd '[:alnum:]' < /dev/urandom | fold -w20 | head -n1)`
    line="$key: $password "
    echo "$line" >> $SV_FILE
    continue
  fi

  echo "$line" >> $SV_FILE

  
done < $SECRET_VARS_TEMPLATE_FILE

#read

mv -f $SV_FILE $SECRET_VARS_FILE
trap '' EXIT
exit 0
