---
- name: "Add Docker GPG key"
  ansible.builtin.rpm_key:
    key: "https://download.docker.com/linux/rocky/gpg"
    state: "present"

- name: "Add Docker repository"
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/rocky/docker-ce.repo"
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: "root"
    group: "root"
    mode: "0644"
    checksum: md5:8cf88ac69a2c9c72b7e25fea8398b694
