diyidp_users:
  -
    uid: ["student1"]
    cn: ["Student One"]
    givenName: ["Student"]
    sn: ["One"]
    mail: ["student1@diy.surfconext.nl"]
    displayName: ["Student One"]
    schacHomeOrganization: ["diy.surfconext.nl"]
    username: ["student1"]
    eduPersonAffiliation: ["member"]
    isMemberOf: ["urn:collab:org:surf.nl"]
    schacPersonalUniqueCode: ["urn:schac:personalUniqueCode:nl:local:diy.surfconext.nl:studentid:123456"]
    eduPersonScopedAffiliation: ["member@cs.diy.surfconext.nl"]
  -
    uid: ["FyHah7$J"]
    cn: ["Student Two"]
    givenName: ["Student"]
    sn: ["Two"]
    mail: ["s1869831907@example.org"]
    displayName: ["Student Two"]
    schacHomeOrganization: ["diy.surfconext.nl"]
    username: ["student2"]
    eduPersonAffiliation: ["member"]
    isMemberOf: ["urn:collab:org:surf.nl"]
    schacPersonalUniqueCode: ["urn:schac:personalUniqueCode:nl:local:diy.surfconext.nl:studentid:223456"]
    eduPersonScopedAffiliation: ["member@cs.diy.surfconext.nl"]
  -
    uid: ["student3"]
    sn: ["Three"]
    mail: ["student3@diy.surfconext.nl"]
    displayName: ["Student Three"]
    schacHomeOrganization: ["diy.surfconext.nl"]
    username: ["student3"]
    eduPersonAffiliation: ["member"]
    isMemberOf: ["urn:collab:org:surf.nl"]
    schacPersonalUniqueCode: ["urn:schac:personalUniqueCode:nl:local:diy.surfconext.nl:studentid:323456"]
    eduPersonScopedAffiliation: ["member@physics2.diy.surfconext.nl"]
  -
    uid: ["viggo7"]
    cn: ["Christian Godfried Viggo Lind"]
    givenName: ["Godfried"]
    sn: ["Viggo"]
    mail: ["Godfried.Viggo@unidenmark-example.dk"]
    displayName: ["Godfried Viggo"]
    schacHomeOrganization: ["unidenmark-example.dk"]
    username: ["student4"]
    eduPersonAffiliation: ["student"]
    isMemberOf: ["urn:collab:org:surf.nl"]
    schacPersonalUniqueCode: ["urn:schac:personalUniqueCode:nl:local:unidenmark-example.dk:studentid:323456"]
  -
    uid: ["U3342109"]
    cn: ["髙橋 大輔"]
    givenName: ["Daisuke"]
    sn: ["Takahashi"]
    mail: ["U3342109@exchange-example.edu"]
    displayName: ["Daisuke Takahashi"]
    schacHomeOrganization: ["exchange-example.edu"]
    username: ["student5"]
    eduPersonAffiliation: ["member"]
    isMemberOf: ["urn:collab:org:exchange-university.org"]
    schacPersonalUniqueCode: ["urn:schac:personalUniqueCode:nl:local:exchange-example.edu:studentid:s123456"]
    eduPersonScopedAffiliation: ["member@phys.exchange-example.edu"]
  -
    uid: ["U6789003"]
    cn: ["Phùng Thị Lệ Tư"]
    givenName: ["Phùng Thị"]
    sn: ["Lệ Tư"]
    mail: ["U6789003@exchange-example.edu"]
    displayName: ["Phùng Thị Lệ Tư"]
    schacHomeOrganization: ["home-university-example.org"]
    username: ["student6"]
    eduPersonAffiliation: ["member"]
    isMemberOf: ["urn:collab:org:surf.nl"]
    schacPersonalUniqueCode: ["urn:schac:personalUniqueCode:nl:local:uniamsterdam-example.nl:studentid:123456"]
    eduPersonScopedAffiliation: ["member@phys.home-university-example.org"]
  -
    uid: ["jsanden"]
    cn: ["Jaantje van der Sanden"]
    givenName: ["Jaantje"]
    sn: ["van der Sanden"]
    mail: ["jsanden@uniamsterdam-example.nl"]
    displayName: ["Jaantje van der Sanden"]
    schacHomeOrganization: ["uniamsterdam-example.nl"]
    password: ["student7"]
    username: ["student7"]
    eduPersonEntitlement: ["urn:x-surfnet:surf.nl:surfdrive-example:quota:50"]
    eduPersonAffiliation: ["member"]
    isMemberOf: ["urn:collab:org:surf.nl"]
    schacPersonalUniqueCode: ["urn:schac:personalUniqueCode:nl:local:uniamsterdam-example.nl:studentid:123456"]
    eduPersonScopedAffiliation: ["member@acounting.uniamsterdam-example.nl"]
  -
    uid: ["s445599"]
    cn: ["Alessandra Gómez Llarnas"]
    givenName: ["Alessandra"]
    sn: ["Gómez Llarnas"]
    mail: ["s445599@universitatmadrid-example.es"]
    displayName: ["Alessandra Gómez Llarnas"]
    schacHomeOrganization: ["universitatmadrid-example"]
    username: ["student8"]
    eduPersonAffiliation: ["member"]
    isMemberOf: ["urn:collab:org:surf.nl"]
    schacPersonalUniqueCode: ["urn:schac:personalUniqueCode:nl:local:universitatmadrid-example:studentid:123456"]
    eduPersonScopedAffiliation: ["member@acounting.test.cs.universitatmadrid-example"]
  -
    uid: ["abriseno"]
    cn: ["Augustus Padrón Briseño"]
    givenName: ["August"]
    sn: ["Briseño"]
    mail: ["A.Briseno@universitatmadrid-example.es"]
    displayName: ["August Briseño"]
    schacHomeOrganization: ["universitatmadrid-example.es"]
    username: ["student9"]
    eduPersonAffiliation: ["member"]
    isMemberOf: ["urn:collab:org:surf.nl"]
    schacPersonalUniqueCode: ["urn:schac:personalUniqueCode:nl:local:universitatmadrid-example:studentid:S123456"]
    eduPersonScopedAffiliation: ["member@students.universitatmadrid-example.es"]
  -
    uid: ["s134567"]
    cn: ["邵靜宜"]
    givenName: ["Shao"]
    sn: ["Jingy"]
    mail: ["s134567@pkuni.edu-example.cn"]
    displayName: ["Shao Jingy"]
    schacHomeOrganization: ["pkuni.edu-example.cn"]
    username: ["student10"]
    eduPersonAffiliation: ["member"]
    isMemberOf: ["urn:collab:org:surf.nl"]
    schacPersonalUniqueCode: ["urn:schac:personalUniqueCode:nl:local:pkuni.edu-example.cn:studentid:s10513456"]
    eduPersonScopedAffiliation: ["member@students.2010.pkuni.edu-example.cn"]
  -
    uid: ["U9088123"]
    cn: ["Roman Švejda"]
    givenName: ["Roman"]
    sn: ["Švejda"]
    mail: ["U9088123@uni.poznantech-example.pl"]
    displayName: ["Roman Švejda"]
    schacHomeOrganization: ["uni.poznantech-example.pl"]
    username: ["student11"]
    eduPersonAffiliation: ["member"]
    isMemberOf: ["urn:collab:org:surf.nl"]
    schacPersonalUniqueCode: ["urn:schac:personalUniqueCode:nl:local:uni.poznantech-example.pl:studentid:S123456"]
    eduPersonScopedAffiliation: ["member@cs.uni.poznantech-example.pl"]
  -
    uid: ["U7128109"]
    cn: ["Anna Rybínová"]
    givenName: ["Anna"]
    sn: ["Rybínová"]
    mail: ["U7128109@uni.poznantech-example.pl"]
    displayName: ["Anna Rybínová"]
    schacHomeOrganization: ["uni.poznantech-example.pl"]
    username: ["student12"]
    eduPersonAffiliation: ["member"]
    isMemberOf: ["urn:collab:org:surf.nl"]
    schacPersonalUniqueCode: ["urn:schac:personalUniqueCode:nl:local:uni.poznantech-example.pl:studentid:S124456"]
    eduPersonScopedAffiliation: ["member@cs.uni.poznantech-example.pl"]
  -
    uid: ["p0987743"]
    cn: ["Li Qin Ch'ien"]
    givenName: ["Li Qin"]
    sn: ["Ch'ien"]
    mail: ["p0987743@pkuni.edu-example.cn"]
    displayName: ["Li Qin Ch'ien"]
    schacHomeOrganization: ["pkuni.edu-example.cn"]
    username: ["student13"]
    eduPersonAffiliation: ["student"]
    isMemberOf: ["urn:collab:org:surf.nl"]
    schacPersonalUniqueCode: ["urn:schac:personalUniqueCode:nl:local:pkuni.edu-example.cn:studentid:1124456"]
    eduPersonScopedAffiliation: ["student@pkuni.edu-example.cn"]
  -
    uid: ["student15"]
    cn: ["Sander Johan Kjær"]
    givenName: ["Sander"]
    sn: ["Kjær"]
    mail: ["kjaer11@stockholmuni-example.se"]
    displayName: ["Sander J. Kjær"]
    schacHomeOrganization: ["stockholmuni-example.se"]
    username: ["student15"]
    eduPersonAffiliation: ["student"]
    isMemberOf: ["urn:collab:org:surf.nl"]
    schacPersonalUniqueCode: ["urn:schac:personalUniqueCode:nl:local:stockholmuni-example.se:studentid:223456"]
    eduPersonScopedAffiliation: ["student@23.stockholmuni-example.se"]
  -
    uid: ["student16"]
    cn: ["Erôss Neci"]
    givenName: ["Erôss"]
    sn: ["Neci"]
    mail: ["eross.neci@kuni.edu-example.tr"]
    displayName: ["Erôss Neci"]
    schacHomeOrganization: ["kuni.edu-example.tr"]
    username: ["student16"]
    eduPersonAffiliation: ["employee"]
    isMemberOf: ["urn:collab:org:surf.nl"]
    schacPersonalUniqueCode: ["urn:schac:personalUniqueCode:nl:local:kuni.edu-example.tr:studentid:123456"]
    eduPersonScopedAffiliation: ["employee@2015.kuni.edu-example.tr"]
  -
    uid: ["student16"]
    cn: ["Erôss Neci"]
    givenName: ["Erôss"]
    sn: ["Neci"]
    mail: ["eross.neci@kuni.edu-example.tr"]
    displayName: ["Erôss Neci"]
    schacHomeOrganization: ["kuni.edu-example.tr"]
    username: ["student16"]
    eduPersonEntitlement: ["urn:mace:terena.org:tcs:personal-user-example"]
    eduPersonAffiliation: ["staff"]
    isMemberOf: ["urn:collab:org:co-example.org"]
    schacPersonalUniqueCode: ["urn:schac:personalUniqueCode:nl:local:kuni.edu-example.tr:studentid:123456"]
    eduPersonScopedAffiliation: ["staff@2015.kuni.edu-example.tr"]
  -
    uid: ["student18"]
    cn: ["Marjanca Muršić"]
    givenName: ["Marjanca"]
    sn: ["Muršić"]
    mail: ["Marjanca.Mursic@kuni.edu-example.tr"]
    displayName: ["Marjanca Muršić"]
    schacHomeOrganization: ["kuni.edu-example.tr"]
    username: ["student18"]
    eduPersonAffiliation: ["student"]
    isMemberOf: ["urn:collab:org:surf.nl"]
    schacPersonalUniqueCode: ["urn:schac:personalUniqueCode:nl:local:kuni.edu-example.tr:studentid:s123456"]
    eduPersonScopedAffiliation: ["student@1234.kuni.edu-example.tr"]
  -
    uid: ["student19"]
    cn: ["Petra Penttilä"]
    givenName: ["Petra"]
    sn: ["Penttilä"]
    mail: ["ppentila@hotmail-example.org"]
    displayName: ["Petra Penttilä"]
    schacHomeOrganization: ["university-example.org"]
    username: ["student19"]
    eduPersonAffiliation: ["student"]
    isMemberOf: ["urn:collab:org:surf.nl"]
    schacPersonalUniqueCode: ["urn:schac:personalUniqueCode:nl:local:unidenmark-example.dk:studentid:123456"]
    eduPersonScopedAffiliation: ["student@test.university-example.org"]
  -
    uid: ["student20"]
    cn: ["Jóney Ingólfsdóttir"]
    givenName: ["Jóney"]
    sn: ["Ingólfsdóttir"]
    mail: ["Joney.Ingolfsdottir@unidenmark-example.dk"]
    displayName: ["Jóney Ingólfsdóttir"]
    schacHomeOrganization: ["unidenmark-example.dk"]
    username: ["student20"]
    eduPersonAffiliation: ["student"]
    isMemberOf: ["urn:collab:org:surf.nl"]
    schacPersonalUniqueCode: ["urn:schac:personalUniqueCode:nl:local:unidenmark-example.dk:studentid:s20513456"]
